version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: fase4pedido-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: fase4pedido
    ports:
      - "27019:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fase4pedido-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  fase4-pedido:
    image: fase4-pedido:latest
    container_name: fase4-pedido-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/fase4pedido
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: